services:
  - type: web
    name: calendar-assistant
    env: node
    buildCommand: |
    apt-get update && apt-get install -y chromium chromium-browser
    npm install --production=false  # This installs dev dependencies too
    npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calendar-assistant-db
          property: connectionString
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
